// Generated by https://quicktype.io

export interface Basket {
  id:                            number;
  owner:                         string;
  status:                        string;
  lines:                         string;
  url:                           string;
  total_excl_tax:                string;
  total_excl_tax_excl_discounts: string;
  total_incl_tax:                string;
  total_incl_tax_excl_discounts: string;
  total_tax:                     string;
  currency:                      null;
  voucher_discounts:             any[];
  offer_discounts:               any[];
  is_tax_known:                  boolean;
}


export interface AddProduct {
  url:      string;
  quantity: number;
  options?:  Option[];
}

export interface Option {
  option: string;
  value:  string;
}


export interface Voucher {
  vouchercode: string;
}

